name = "txpipe-shop/aletheia"
version = "0.1.0"
compiler = "v1.1.22"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'txpipe-shop/aletheia'"

[repository]
user = "txpipe-shop"
project = "aletheia"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v3.1.0"
source = "github"

[config]
